### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by AdrianVovk** [Sexual/selly-ui#1]
Hi! I am pinging you from [Substance Mobile](https://github.com/SubstanceMobile) to ask you if you would be willing to rename your theme and syntax highlighting packages to something more work-appropriate for it to be included as the defult theme in an upcoming IDE based on Atom. Thanks!

**Comment by AdrianVovk** [comment]
No guarentees, but it might happen. Feel free to email me at avovk@substanceproject.net

**Comment by Sexual** [comment]
Yes, I'll push through an update in an hour or so for both packages.

**Comment by AdrianVovk** [comment]
It is done. https://github.com/AdrianVovk/low
